# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for managed runs. These include runs against
# the localdocker, remotedocker, and cluster compute targets.

# Note that this file is NOT used to automatically manage dependencies for the
# local compute target. To provision these dependencies locally, run:
# conda env update --file conda_dependencies.yml

# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

# For managing Spark packages and configuration, see spark_dependencies.yml.
# Version of this configuration file's structure and semantics in AzureML.
# This directive is stored in a comment to preserve the Conda file structure.
# [AzureMlVersion] = 2

# These dependencies are used to create the environment used by the batch score 
# pipeline step
name: diabetes_regression_scoring_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.7.*
  - pip

  - pip:
      # Base AzureML SDK
      - azureml-sdk==1.6.*
      
      # Scoring deps
      - scikit-learn
      - pandas

      # Observability
      - opencensus==0.7.7
      - opencensus-context==0.1.1
      - opencensus-ext-azure==1.0.2
      - python-dotenv==0.10.3

      # Data Classes
      - dataclasses
