pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ml_service/util/create_scoring_image.py
    - ml_service/util/Dockerfile
    - code/scoring/
    exclude:
    - code/scoring/deployment_config_aci.yml
    - code/scoring/deployment_config_aks.yml    

pool: 
  vmImage: 'ubuntu-latest'

container: mcr.microsoft.com/mlops/python:latest

variables:
- group: devopsforai-aml-vg
- name: 'SCORE_SCRIPT'
  value: 'score.py'

name: $(Date:yyyyMMdd)$(Rev:r)
steps:

- bash: |
   # Invoke the Python building and publishing a training pipeline with Python on ML Compute
   python3 $(Build.SourcesDirectory)/ml_service/util/create_scoring_image.py   
  failOnStderr: 'false'
  env:
    SP_APP_SECRET: '$(SP_APP_SECRET)'
    MODEL_VERSION: 1
  displayName: 'Create Scoring Image'
  enabled: 'true'

