# Pipeline to run basic code quality tests as part of pull requests to the master branch.

resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest

trigger: none
pr:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

container: mlops

variables:
- template: diabetes_regression-variables.yml
- group: devopsforai-aml-vg

steps:
- template: azdo-base-pipeline.yml
