pr: none
trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

container:
  image: mlopscr.azurecr.io/public/mlops/mlopspython:latest
  endpoint: acrconnection


variables:
- group: devopsforai-aml-vg


steps:
- script: |
   ls -ltr
   echo 'hi'
   flake8 --output-file=$(Build.BinariesDirectory)/flake8_testresults.xml --format junit-xml  
   cat $(Build.BinariesDirectory)/flake8_testresults.xml
   ls -ltr $(Build.BinariesDirectory)
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Run code quality tests'
  enabled: 'true'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '$(Build.BinariesDirectory)/*_testresults.xml'
    testRunTitle: 'Linitnig'
    failTaskOnFailedTests: true
  displayName: 'Publish linting results'
  enabled: 'true'
  

    
- bash: |
   # Invoke the Python training pipeline
   python3 $(Build.SourcesDirectory)/aml_pipelines/model_train_pipeline.py
  failOnStderr: 'false'
  env:
    SP_APP_SECRET: '$(SP_APP_SECRET)'
  displayName: 'Train model using AML with Remote Compute'
  enabled: 'true'